---

name: stash action
inputs:
  name:
    description: 'Stash name'
    default: 'stash'
  path:
    description: 'A directory that describes what to stash'
    required: true

runs:
  using: "composite"
  steps:
    - name: Create stash
      run: tar -acf "${{ runner.temp }}/${ARTIFACT_NAME}".tar.zst -C "${ARTIFACT_PATH}" ./
      shell: bash
      env:
        ARTIFACT_NAME: ${{ inputs.name }}
        ARTIFACT_PATH: ${{ inputs.path }}

    - name: Upload stash
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.name }}
        path: ${{ runner.temp }}/${{ inputs.name }}.tar.zst
