
name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, edited, milestoned]
  pull_request:
    types: [opened, edited, milestoned]
env:
  MY_GITHUB_TOKEN: ${{ secrets.APM_TECH_USER_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign milestoned to Project
    steps:
    - name: Assign issues and pull requests with milestones to project
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: github.event.issue.milestone || github.event.pull_request.milestone
      with:
        project: 'https://github.com/orgs/elastic/projects/454'
        column_name: 'Planned'